### ISSUE TITLE
No reminders for most recent tags

### ISSUE THREAD

**Issue by dalevross** [shalvah/RemindMeOfThisTweet#15]
Maybe I was added to some filter but in the event it's a bug I'm adding it here.

https://twitter.com/search?q=from%3Adalevross%20%40RemindMe_OfThis&src=typed_query&f=live

**Comment by shalvah** [comment]
+1 for linking to the search results.

Do you have push notifications enabled on remindmeofthis.app?

**Comment by dalevross** [comment]
I believe I had set it but could be confusing that with this_vid. Is that a requirement? I want it set though so will double-check now.

**Comment by dalevross** [comment]
@shalvah Apparently, it was set for my account, possibly when I was using Chrome. I'm now using Brave so I tried toggling it but it logged an error in the console "An error occurred while retrieving token.  DOMException: Registration failed - push service not available"
```
function requestPermission(button) {
        Notification.requestPermission()
                .then((permission) => {
                    if (permission === 'granted') {
                        console.log('Notification permission granted.');
                        button.disabled = true;
                        button.textContent = "Loading...";

                        messaging.getToken().then((currentToken) => {
                            console.log({currentToken});
                            if (currentToken) {
                                submitNotificationUpdateForm(['notifications.enabled', 1], ['notifications.fbtoken', currentToken]);
                            } else {
                                console.log('No Instance ID token available.');
                            }
                        }).catch((err) => {
                           /*Error was logged from here*/

                            console.log('An error occurred while retrieving token. ', err);
                        });
                    } else {
                        console.log('Unable to get permission to notify.');
                    }
                });
    }
```

**Comment by dalevross** [comment]
This could be related.
https://github.com/brave/brave-browser/issues/2143

**Comment by shalvah** [comment]
Yes, Brave is not one of the supported browsers.
I suspect that it's been sending notifications to your Chrome, but perhaps you have notification access turned off or something?
