### ISSUE TITLE
Windows 10 Google Chrome push notification does nothing when clicked.

### ISSUE THREAD

**Issue by jordanmack** [shalvah/RemindMeOfThisTweet#16]
When I receive a push notification in Windows 10 Google Chrome it shows up in Notification Center saying "Click to view tweet". When clicked it disappears and nothing happens.

**Comment by shalvah** [comment]
This is an issue when using Windows 10' native notifications. I can't do anything about that. You can switch back to Chrome notifications instead from chrome://flags. See https://support.google.com/chrome/thread/3210517?hl=en

**Comment by jordanmack** [comment]
Thanks.
