### ISSUE TITLE
No longer getting replies from bot

### ISSUE THREAD

**Issue by avalyn2** [shalvah/RemindMeOfThisTweet#17]
Example:

https://twitter.com/curefans/status/1226456764385767425?s=19

**Comment by protectyourkeys** [comment]
I’m having the same issue. Bot won’t respond

**Comment by shalvah** [comment]
Twitter has a replies limit. Can't send more than 25 tweets every 15 minutes. So sometimes we hit that limit.

I'd recommend enabling push notifications on remindmeofthis.app. That way you'll get your reminder either way. I should probably also add a confirmation notification.
