### ISSUE TITLE
BOT does not reply back

### ISSUE THREAD

**Issue by avalyn2** [shalvah/RemindMeOfThisTweet#19]
Example:

https://twitter.com/curefans/status/1328048292253536256

no reply back from bot.

**Comment by shalvah** [comment]
It's not two years yet nah.😐

Also: Twitter has limitations on how many tweets you can post. Enable push notifications at https://remindmeofthis.app/settings so you don't miss the actual reminder.

![Screenshot_20201116-125910~2](https://user-images.githubusercontent.com/14361073/99250301-bc124f80-280b-11eb-8c24-1147f8c92a16.jpg)
