### ISSUE TITLE
RemindMe happily schedules dates in the past

### ISSUE THREAD

**Issue by tsahi** [shalvah/RemindMeOfThisTweet#20]
I accidentally asked for a reminder on January 2020 instead of 2021. RemindMe had no issue, and replied it will remind me when the date comes. It should recognize that the date is in the past, and reply with an error message.
![תמונה](https://user-images.githubusercontent.com/2961084/99812289-edae5200-2b4e-11eb-95f9-dcd6bb3a4ff6.png)

**Comment by shalvah** [comment]
Haha, thanks. That's strange because there's logic that fails the reminder if the time is in the past. I'll get to it when I have some time.

**Comment by shalvah** [comment]
Fixed!
