### ISSUE TITLE
Limit reminder duration

### ISSUE THREAD

**Issue by shalvah** [shalvah/RemindMeOfThisTweet#28]
People shouldn't be able to set reminders for a 100 years in the future.😕 Let's cap it at say, 30 years.

Fixing this should be pretty straightforward—add a maximum reminder time (there's already a `minimumReminderTime`):

https://github.com/shalvah/RemindMeOfThisTweet/blob/54391d1db98a4ca3046a09401b666e1fbd015f5d/src/factory.service.js#L28

(If you work on this, don't forget to add a test; you can follow the minimum reminder time test, or let me know if you need help.)

**Comment by olucurious** [comment]
Just sent a PR here https://github.com/shalvah/RemindMeOfThisTweet/pull/29
Let me know what you think

**Comment by shalvah** [comment]
Fixed in https://github.com/shalvah/RemindMeOfThisTweet/pull/29
