### ISSUE TITLE
view reminders

### ISSUE THREAD

**Issue by sjorsvanheuveln** [shalvah/RemindMeOfThisTweet#37]
Would be great to have a command that returns all outstanding reminders of my Twitter handle.

**Comment by shalvah** [comment]
Yeah, it would be. Unfortunately, that's almost certainly never happening. Reminders are stored in Redis, keyed by date/time. Searching for all reminders of a particular user will mean iterating through every key. Unfortunate design tradeoff: really efficient for scheduling reminders, but terrible for most other things.
