### ISSUE TITLE
Reminder not received. Was I  doing something wrong?

### ISSUE THREAD

**Issue by sebrock** [shalvah/RemindMeOfThisTweet#38]
https://twitter.com/DudeJLebowski/status/1601548151332085760
https://twitter.com/RemindMe_OfThis/status/1601588627326246913

**Comment by shalvah** [comment]
"Twitter has a reply limit, so we won't be able to respond to every tweet.😢
To get around that, sign in and enable push notifications:"
 https://remindmeofthis.app/#:~:text=Twitter%20has%20a%20reply%20limit%2C%20so%20we%20won%27t%20be%20able%20to%20respond%20to%20every%20tweet.%F0%9F%98%A2%0ATo%20get%20around%20that%2C%20sign%20in%20and%20enable%20push%20notifications%3A

I'd put this in the bio, or as part of replies, but y'know... Limits.
