### ISSUE TITLE
Improve date/time parsing

### ISSUE THREAD

**Issue by shalvah** [shalvah/RemindMeOfThisTweet#5]
Here are some requests which fail to parse currently:

- "in 2023"
- "4 hours" (no "in")
- "in 6 months"

**Comment by shalvah** [comment]
Also, something like "by 12:45 am" used in the middle of the day seems to refer to the past 12:45 instead of wrapping, even though the `forwardDate` option is specified.

**Comment by shalvah** [comment]
https://twitter.com/xchurlx/status/1132742758102425604?s=19j


https://twitter.com/Delftsey/status/1148307327340167173?s=19


https://twitter.com/nytafili/status/1148306855753465857?s=19

https://twitter.com/Dehddy_/status/1148283228119343105?s=19

**Comment by shalvah** [comment]
Solved (mostly) in #

**Comment by shalvah** [comment]
https://twitter.com/simi_giwa/status/1150892610334199808?s=19

My guess is: two objects with time. Interesting.

**Comment by shalvah** [comment]
https://mobile.twitter.com/triplerolex/status/1166069397385076738

**Comment by tsahi** [comment]
For unexpected formats, you might have better luck using some AI. I've used Azure Cognitive Services successfully: https://azure.microsoft.com/en-us/overview/ they also have a free tier in some regions.

**Comment by shalvah** [comment]
Maybe, but I think it would be faster with local parsing (plus no rate limits). I'll only switch to an API if there are significant problems

**Comment by tsahi** [comment]
I meant this link actually: https://azure.microsoft.com/en-us/services/cognitive-services/language-understanding-intelligent-service/ but OK.
